web: cd backend && uv run gunicorn src.wsgi:application --bind 0.0.0.0:$PORT --workers 2
{% if cookiecutter.use_celery == "y" %}
worker: cd backend && uv run celery -A src worker -l info
beat: cd backend && uv run celery -A src beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
{% endif %}
